### ISSUE TITLE
db connection error

### ISSUE THREAD

**Issue by 1988gadocansey** [jericklasat/golang-fiber-boilerplate#1]
FTL Error while connecting to database error="cannot parse `user= host= password=xxxxx dbname= port=0 sslmode=disable TimeZone=`: invalid port (outside range)"

**Comment by jericklasat** [comment]
hi @1988gadocansey may I know what your config is? have you added changes in .env?

**Comment by 1988gadocansey** [comment]
I got it.  Sorry i thought you were you seen postgres found out it was mysql. thanks 

I have changed the DB to postgres 

DB_HOST: localhost
DB_PORT: 5432

DB_USERNAME: gadocansey
DB_PASSWORD: 1988Gadocansey
DB_NAME: Gadness

**Comment by jericklasat** [comment]
Nice to hear that, with regards the Bearer issue did you manage to work it out? I'm debugging it yesterday and my current issue is I'm getting "signature invalid" response.It is known issue in the JWT package.

**Comment by 1988gadocansey** [comment]
I passed Token in the Request Header and it works
