### ISSUE TITLE
Bearer Auth not working

### ISSUE THREAD

**Issue by 1988gadocansey** [jericklasat/golang-fiber-boilerplate#2]
<img width="1049" alt="Screen Shot 2021-09-13 at 2 27 57 PM" src="https://user-images.githubusercontent.com/7513799/133101890-85c0d33a-2785-4754-98c6-0053223a3e10.png">

**Comment by jericklasat** [comment]
I've updated the JWT dependency because github.com/dgrijalva/jwt-go is no longer maintained. I also fixed the bearer issue by using custom claim, you can refer to this commit https://github.com/jericklasat/golang-fiber-boilerplate/commit/7e37f10f60e0ffc44d3577b5303f82155f6efe08
